<?php

/**
 * 29. - Header + Footer CSS
 */
/**
 * 29 – Header + Footer CSS
 * v2.0 – Céljaim kiemelt menüpont
 */
if ( ! defined( 'ABSPATH' ) ) exit;

add_action( 'wp_head', function() {
    $css = ':root{--ch-height:72px;--ch-height-shrink:58px;--ch-bg:rgba(255,255,255,0.92);--ch-bg-shrink:rgba(255,255,255,0.97);--ch-border:#e8ebe9;--ch-text:#1e1e1e;--ch-text-muted:#7c8a83;--ch-accent:#2d6a4f;--ch-accent-light:rgba(45,106,79,0.08);--ch-accent-glow:rgba(45,106,79,0.18);--ch-radius:12px;--ch-radius-sm:8px;--ch-transition:0.25s cubic-bezier(0.4,0,0.2,1);--ch-shadow:0 1px 3px rgba(0,0,0,0.04),0 4px 24px rgba(0,0,0,0.03);--ch-shadow-shrink:0 2px 12px rgba(0,0,0,0.06),0 8px 32px rgba(0,0,0,0.04);--cf-bg:#1a2e23;--cf-bg-light:#223a2d;--cf-text:#c8d6ce;--cf-text-muted:#7c9a88;--cf-heading:#e8f0eb;--cf-accent:#40b882;--cf-accent-soft:rgba(64,184,130,0.12);--cf-border:rgba(255,255,255,0.06);--cf-bottom-bg:#142219}';

    $css .= '.ch-header{position:fixed;top:0;left:0;width:100%;height:var(--ch-height);background:var(--ch-bg);backdrop-filter:blur(16px);-webkit-backdrop-filter:blur(16px);border-bottom:1px solid var(--ch-border);z-index:9999;transition:height var(--ch-transition),background var(--ch-transition),box-shadow var(--ch-transition)}.ch-header.is-scrolled{height:var(--ch-height-shrink);background:var(--ch-bg-shrink);box-shadow:var(--ch-shadow-shrink)}body{padding-top:var(--ch-height)!important;transition:padding-top var(--ch-transition)}body.ch-scrolled{padding-top:var(--ch-height-shrink)!important}.admin-bar .ch-header{top:32px}@media(max-width:782px){.admin-bar .ch-header{top:46px}}';

    $css .= '.ch-container{max-width:1280px;margin:0 auto;padding:0 24px;height:100%;display:flex;align-items:center;justify-content:space-between}.ch-logo{display:flex;align-items:center;gap:10px;text-decoration:none;flex-shrink:0}.ch-logo-icon{font-size:26px;line-height:1;transition:transform var(--ch-transition)}.ch-logo:hover .ch-logo-icon{transform:rotate(-12deg) scale(1.1)}.ch-logo-text{font-size:20px;font-weight:700;color:var(--ch-text);letter-spacing:-0.3px;line-height:1.2}.ch-logo-accent{color:var(--ch-accent)}';

    $css .= '.ch-nav{display:flex;align-items:center}.ch-menu{list-style:none;margin:0;padding:0;display:flex;align-items:center;gap:4px}.ch-menu-item{position:relative}.ch-menu-link{display:flex;align-items:center;gap:4px;padding:8px 16px;font-size:14.5px;font-weight:500;color:var(--ch-text-muted);text-decoration:none;border-radius:var(--ch-radius-sm);white-space:nowrap;transition:color var(--ch-transition),background var(--ch-transition)}.ch-menu-link:hover{color:var(--ch-accent);background:var(--ch-accent-light)}.ch-menu-item.is-active>.ch-menu-link,.ch-menu-item.current-menu-item>.ch-menu-link,.ch-menu-item.current-menu-ancestor>.ch-menu-link{color:var(--ch-accent);background:var(--ch-accent-light);font-weight:600}.ch-menu-item.is-active>.ch-menu-link::after,.ch-menu-item.current-menu-item>.ch-menu-link::after{content:"";position:absolute;bottom:-1px;left:16px;right:16px;height:2px;background:var(--ch-accent);border-radius:2px}.ch-chevron{transition:transform var(--ch-transition);opacity:.5}.ch-menu-item.has-submenu:hover .ch-chevron{transform:rotate(180deg);opacity:1}';

    $css .= '.ch-submenu{position:absolute;top:calc(100% + 8px);left:0;min-width:200px;background:#fff;border:1px solid var(--ch-border);border-radius:var(--ch-radius);box-shadow:0 12px 40px rgba(0,0,0,0.08);padding:8px;list-style:none;opacity:0;visibility:hidden;transform:translateY(-8px);transition:opacity var(--ch-transition),transform var(--ch-transition),visibility var(--ch-transition)}.ch-menu-item.has-submenu:hover>.ch-submenu{opacity:1;visibility:visible;transform:translateY(0)}.ch-submenu-link{display:block;padding:10px 14px;font-size:14px;font-weight:450;color:var(--ch-text);text-decoration:none;border-radius:var(--ch-radius-sm);transition:color var(--ch-transition),background var(--ch-transition)}.ch-submenu-link:hover{color:var(--ch-accent);background:var(--ch-accent-light)}.ch-submenu-item.is-active .ch-submenu-link{color:var(--ch-accent);font-weight:600}';

    $css .= '.ch-header-actions{display:flex;align-items:center;gap:10px;margin-left:16px;flex-shrink:0}';

    /* ═══ CÉLJAIM – KIEMELT MENÜPONT ═══ */
    $css .= '.ch-menu-item--celjaim{margin-left:4px}';
    $css .= '.ch-menu-link--celjaim{background:linear-gradient(135deg,#2d6a4f,#40916c)!important;color:#fff!important;font-weight:600!important;padding:7px 18px!important;border-radius:999px!important;font-size:13.5px!important;gap:6px!important;box-shadow:0 2px 8px rgba(45,106,79,0.2);transition:all var(--ch-transition)!important}';
    $css .= '.ch-menu-link--celjaim svg{color:#fff!important;stroke:#fff!important;width:15px;height:15px;flex-shrink:0}';
    $css .= '.ch-menu-link--celjaim:hover{background:linear-gradient(135deg,#245a42,#358a60)!important;color:#fff!important;box-shadow:0 4px 16px rgba(45,106,79,0.3)!important;transform:translateY(-1px)}';
    $css .= '.ch-menu-item--celjaim.is-active .ch-menu-link--celjaim{background:linear-gradient(135deg,#1b4d3e,#2d6a4f)!important;box-shadow:0 2px 12px rgba(45,106,79,0.35)!important}';
    $css .= '.ch-menu-item--celjaim.is-active>.ch-menu-link--celjaim::after{display:none}';

    /* Mobil céljaim */
    $css .= '.ch-mobile-item--celjaim{margin-top:4px;padding-top:8px;border-top:1px solid #e8ebe9}';
    $css .= '.ch-mobile-link--celjaim{background:linear-gradient(135deg,#2d6a4f,#40916c)!important;color:#fff!important;font-weight:600!important;border-radius:var(--ch-radius-sm)!important;margin:4px 4px!important}';
    $css .= '.ch-mobile-link--celjaim svg.ch-mobile-icon,.ch-mobile-item--celjaim svg.ch-mobile-icon{color:#fff!important;stroke:#fff!important}';
    $css .= '.ch-mobile-link--celjaim span{color:#fff!important}';
    $css .= '.ch-mobile-link--celjaim:hover{background:linear-gradient(135deg,#245a42,#358a60)!important;color:#fff!important}';
    $css .= '.ch-mobile-item--celjaim.is-active .ch-mobile-link--celjaim{background:linear-gradient(135deg,#1b4d3e,#2d6a4f)!important}';
    $css .= '.ch-mobile-item--celjaim.is-active::before{background:#fff!important}';

    $css .= 'button#ch-hamburger,button#ch-hamburger:hover,button#ch-hamburger:active,button#ch-hamburger:focus,button#ch-hamburger:focus-visible,.ch-hamburger,.ch-hamburger:hover,.ch-hamburger:active,.ch-hamburger:focus,.ch-hamburger:focus-visible,.ch-hamburger.is-open{display:none;flex-direction:column;justify-content:center;align-items:center;width:44px;height:44px;padding:0;background:transparent!important;border:none!important;outline:none!important;box-shadow:none!important;cursor:pointer;gap:5px;border-radius:var(--ch-radius-sm);color:#1e1e1e!important;-webkit-appearance:none!important;-webkit-tap-highlight-color:transparent;transition:background .2s ease}button#ch-hamburger:hover,.ch-hamburger:hover{background:rgba(45,106,79,0.08)!important}';

    $css .= '.ch-hamburger-line{display:block;width:22px;height:2px;background:#1e1e1e!important;border-radius:2px;transition:transform .25s cubic-bezier(.4,0,.2,1),opacity .25s cubic-bezier(.4,0,.2,1)}.ch-hamburger.is-open .ch-hamburger-line:nth-child(1){transform:translateY(7px) rotate(45deg)}.ch-hamburger.is-open .ch-hamburger-line:nth-child(2){opacity:0}.ch-hamburger.is-open .ch-hamburger-line:nth-child(3){transform:translateY(-7px) rotate(-45deg)}';

    $css .= '.ch-mobile-overlay{position:fixed;top:0;left:0;right:0;bottom:0;width:100%;height:100%;height:100dvh;z-index:100000;pointer-events:none;visibility:hidden}.ch-mobile-overlay::before{content:"";position:absolute;inset:0;background:rgba(0,0,0,0);transition:background .3s ease}.ch-mobile-overlay.is-open{pointer-events:auto;visibility:visible}.ch-mobile-overlay.is-open::before{background:rgba(0,0,0,0.4)}.ch-mobile-panel{position:absolute;top:0;right:0;width:300px;max-width:85vw;height:100%;height:100dvh;background:#fff;box-shadow:-4px 0 32px rgba(0,0,0,0.12);display:flex;flex-direction:column;overflow:hidden;transform:translate3d(100%,0,0);will-change:transform;transition:transform .32s cubic-bezier(.32,.72,0,1);z-index:2}.ch-mobile-overlay.is-open .ch-mobile-panel{transform:translate3d(0,0,0)}';

    $css .= '.ch-mobile-header{display:flex;align-items:center;justify-content:space-between;padding:16px 20px;border-bottom:1px solid #f0f1f3;flex-shrink:0;min-height:60px;background:#fff;position:relative;z-index:3}.ch-mobile-header .ch-logo-icon{font-size:22px}.ch-mobile-header .ch-logo-text{font-size:16px}';

    $css .= 'button.ch-mobile-close,button.ch-mobile-close:hover,button.ch-mobile-close:active,button.ch-mobile-close:focus,button.ch-mobile-close:focus-visible{display:flex!important;align-items:center;justify-content:center;width:36px;height:36px;padding:0;margin:0;border:none!important;outline:none!important;background:#f5f6f5!important;border-radius:50%;cursor:pointer;color:#555!important;flex-shrink:0;z-index:10;-webkit-appearance:none!important;box-shadow:none!important;-webkit-tap-highlight-color:transparent;transition:color .2s ease,background .2s ease,transform .15s ease}button.ch-mobile-close:hover{color:#1e1e1e!important;background:#e8ebe9!important}button.ch-mobile-close:active{transform:scale(.92)}.ch-mobile-close svg{color:inherit!important;stroke:currentColor!important;fill:none!important;width:18px;height:18px;display:block}';

    $css .= '.ch-mobile-nav{flex:1 1 auto;overflow-y:auto;-webkit-overflow-scrolling:touch;padding:8px 12px;min-height:0}.ch-mobile-menu{list-style:none;margin:0;padding:0;display:flex;flex-direction:column;gap:0}.ch-mobile-item{width:100%;flex-shrink:0}.ch-mobile-item+.ch-mobile-item{border-top:1px solid #f0f1f3}.ch-mobile-link{display:flex;align-items:center;gap:14px;padding:15px 16px;font-size:15px;font-weight:500;color:var(--ch-text);text-decoration:none;border-radius:var(--ch-radius-sm);width:100%;transition:color .2s ease,background .2s ease;margin:2px 0}.ch-mobile-link:hover{background:var(--ch-accent-light);color:var(--ch-accent)}.ch-mobile-link:active{background:rgba(45,106,79,0.12)}.ch-mobile-item.is-active .ch-mobile-link,.ch-mobile-item.current-menu-item .ch-mobile-link{background:var(--ch-accent-light);color:var(--ch-accent);font-weight:600}.ch-mobile-item.is-active,.ch-mobile-item.current-menu-item{position:relative}.ch-mobile-item.is-active::before,.ch-mobile-item.current-menu-item::before{content:"";position:absolute;left:0;top:50%;transform:translateY(-50%);width:3px;height:24px;background:var(--ch-accent);border-radius:0 3px 3px 0;z-index:1}';

    $css .= 'svg.ch-mobile-icon,.ch-mobile-icon{width:20px;height:20px;flex-shrink:0;color:var(--ch-text-muted)!important;stroke:var(--ch-text-muted)!important;transition:color .2s ease,stroke .2s ease}.ch-mobile-link:hover svg.ch-mobile-icon{color:var(--ch-accent)!important;stroke:var(--ch-accent)!important}.ch-mobile-item.is-active svg.ch-mobile-icon,.ch-mobile-item.current-menu-item svg.ch-mobile-icon{color:var(--ch-accent)!important;stroke:var(--ch-accent)!important}';

    $css .= '.ch-mobile-auth{padding:16px 20px;border-top:1px solid #f0f1f3;display:flex;flex-direction:column;gap:8px;flex-shrink:0}.ch-mobile-auth:empty{display:none;padding:0;border:none}';

    $css .= '.ch-mobile-footer{padding:16px 20px;border-top:1px solid #f0f1f3;flex-shrink:0;background:#fafbfa}.ch-mobile-social{display:flex;gap:10px;justify-content:center}.ch-social-link{display:flex;align-items:center;justify-content:center;width:38px;height:38px;border-radius:50%;background:#f5f6f5;color:var(--ch-text-muted);text-decoration:none;flex-shrink:0;transition:color var(--ch-transition),background var(--ch-transition),transform var(--ch-transition)}.ch-social-link:hover{background:var(--ch-accent-light);color:var(--ch-accent);transform:translateY(-2px)}';

    $css .= '.cf-footer{margin-top:60px}.cf-main{background:var(--cf-bg);padding:60px 0 40px}.cf-container{max-width:1280px;margin:0 auto;padding:0 24px}.cf-grid{display:grid;grid-template-columns:1.4fr 1fr 1fr 1fr;gap:48px}.cf-logo{display:inline-flex;align-items:center;gap:10px;text-decoration:none;margin-bottom:16px}.cf-logo-icon{font-size:24px}.cf-logo-text{font-size:18px;font-weight:700;color:var(--cf-heading)}.cf-logo-accent{color:var(--cf-accent)}.cf-description{font-size:13.5px;line-height:1.7;color:var(--cf-text-muted);margin:0 0 20px;max-width:280px}.cf-social{display:flex;gap:10px}.cf-social-link{display:flex;align-items:center;justify-content:center;width:38px;height:38px;border-radius:10px;background:var(--cf-bg-light);border:1px solid var(--cf-border);color:var(--cf-text-muted);text-decoration:none;transition:color var(--ch-transition),background var(--ch-transition),border-color var(--ch-transition),transform var(--ch-transition)}.cf-social-link:hover{color:var(--cf-accent);background:var(--cf-accent-soft);border-color:var(--cf-accent);transform:translateY(-2px)}';

    $css .= '.cf-col-title{font-size:13px;font-weight:700;color:var(--cf-heading);text-transform:uppercase;letter-spacing:1px;margin:0 0 20px;padding-bottom:12px;border-bottom:2px solid var(--cf-accent);display:inline-block}.cf-links{list-style:none;margin:0;padding:0}.cf-links li{margin-bottom:4px}.cf-links a{display:inline-flex;align-items:center;gap:6px;padding:7px 10px;font-size:14px;color:var(--cf-text);text-decoration:none;border-radius:var(--ch-radius-sm);transition:color var(--ch-transition),background var(--ch-transition),padding-left var(--ch-transition)}.cf-links a:hover{color:var(--cf-accent);background:var(--cf-accent-soft);padding-left:14px}.cf-badge{display:inline-block;font-size:10px;font-weight:700;padding:2px 7px;border-radius:6px;background:rgba(245,158,11,0.15);color:#F59E0B;letter-spacing:.5px;margin-left:6px;vertical-align:middle}.cf-badge-blue{background:rgba(59,130,246,0.15);color:#60A5FA}.cf-source-note{font-size:11.5px;color:var(--cf-text-muted);margin-top:16px;font-style:italic;line-height:1.5;opacity:.7}';

    $css .= '.cf-bottom{background:var(--cf-bottom-bg);padding:16px 0;border-top:1px solid var(--cf-border)}.cf-bottom .cf-container{display:flex;align-items:center;justify-content:space-between;flex-wrap:wrap;gap:8px}.cf-copyright{font-size:13px;color:var(--cf-text-muted)}.cf-made{font-size:12px;color:var(--cf-text-muted);opacity:.6}';

    $css .= '.ch-back-to-top{position:fixed;bottom:28px;right:28px;width:46px;height:46px;display:flex;align-items:center;justify-content:center;background:var(--ch-accent);color:#fff;border:none;border-radius:14px;cursor:pointer;box-shadow:0 4px 20px rgba(45,106,79,0.3);z-index:9998;opacity:0;visibility:hidden;transform:translateY(16px);transition:opacity var(--ch-transition),visibility var(--ch-transition),transform var(--ch-transition),background var(--ch-transition),box-shadow var(--ch-transition)}.ch-back-to-top.is-visible{opacity:1;visibility:visible;transform:translateY(0)}.ch-back-to-top:hover{background:#245a42;box-shadow:0 6px 28px rgba(45,106,79,0.4);transform:translateY(-3px)}';

    $css .= '@media(max-width:960px){.ch-nav{display:none}button#ch-hamburger,.ch-hamburger{display:flex!important}.cf-grid{grid-template-columns:1fr 1fr;gap:36px}}';

    $css .= '@media(max-width:600px){:root{--ch-height:62px;--ch-height-shrink:52px}.ch-container{padding:0 16px}.ch-logo-text{font-size:17px}.ch-logo-icon{font-size:22px}.cf-main{padding:40px 0 32px}.cf-grid{grid-template-columns:1fr;gap:32px}.cf-description{max-width:100%}.cf-bottom .cf-container{flex-direction:column;text-align:center}.ch-back-to-top{bottom:20px;right:20px;width:42px;height:42px;border-radius:12px}.ch-mobile-header{padding:14px 18px;min-height:56px}.ch-mobile-link{padding:14px 16px;font-size:14.5px}.ch-mobile-footer{padding:14px 18px}.ch-social-link{width:36px;height:36px}}';

    $css .= '@media(max-width:380px){.ch-mobile-header .ch-logo-text{font-size:14px}.ch-mobile-link{padding:12px 14px;font-size:14px;gap:12px}.ch-mobile-nav{padding:6px 10px}}';

    $css .= '@keyframes chFadeInUp{from{opacity:0;transform:translateY(12px)}to{opacity:1;transform:translateY(0)}}.cf-col{animation:chFadeInUp .5s ease both}.cf-col:nth-child(2){animation-delay:.08s}.cf-col:nth-child(3){animation-delay:.16s}.cf-col:nth-child(4){animation-delay:.24s}';

    echo '<style id="dp-header-footer-css">' . $css . '</style>';
}, 20 );
